In [45]:
pip install numpy


In [46]:
import numpy as np

**Numpy Array**

In [47]:
benimListem = [10,20,30]

In [48]:
type(benimListem)

list

In [49]:
np.array(benimListem)

array([10, 20, 30])

In [50]:
matrixListesi = [[10,20,30],[20,30,40],[30,40,50]]

In [51]:
np.array(matrixListesi)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

**Arange**

In [52]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [53]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

**Zeros**

In [55]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [56]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [57]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [58]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

**Linspace**

In [59]:
np.linspace(0,20,4)

array([ 0.        ,  6.66666667, 13.33333333, 20.        ])

**Eye**

In [60]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

**Random**

In [61]:
np.random.randn(4)

array([ 1.38259472, -1.4556824 , -0.12899123, -0.20492793])

In [62]:
np.random.rand(4,4)

array([[0.22716508, 0.81598196, 0.60767648, 0.23158168],
       [0.57421632, 0.82072751, 0.36676014, 0.77077722],
       [0.54605368, 0.98352024, 0.20155164, 0.13818886],
       [0.66793744, 0.31536423, 0.18938542, 0.87714716]])

In [63]:
np.random.randint(1,10)

3

In [64]:
np.random.randint(1,10,5)

array([8, 3, 1, 6, 4])

In [65]:
benimNumpyDizim = np.arange(30)

In [66]:
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [67]:
benimRandomDizim = np.random.randint(0,300,30)

In [68]:
benimRandomDizim

array([250, 203, 152, 176, 189,  87, 180, 193, 179, 177, 294, 206,  10,
        67, 222, 284, 166, 226,  92, 199, 182, 266,  51,  90, 233, 163,
       163, 213, 168, 261])

**Numpy Dizi Methodları**

In [69]:
benimNumpyDizim.reshape(5,6) #dizilerin boyutunu düzenler

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [70]:
benimNumpyDizim.max() # max elemanı verir

29

In [72]:
benimNumpyDizim.min() # min elemanı verir

0

In [73]:
benimRandomDizim.argmax() # max elemanın indexini verir

10

In [74]:
benimRandomDizim.argmin() # min elemanın indexini verir

12

In [77]:
reshapeDizim = benimNumpyDizim.reshape(5,6)

In [78]:
reshapeDizim.shape

(5, 6)