In [69]:
import numpy as np

In [70]:
benimDizim = np.arange(0,15)

In [71]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [72]:
benimDizim[5]

5

In [73]:
benimDizim[3:8]

array([3, 4, 5, 6, 7])

In [74]:
benimDizim[3:8] = -5

In [75]:
benimDizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [76]:
baskaDizi = np.arange(0,24)

In [77]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [78]:
baskaDizi[4:9]

array([4, 5, 6, 7, 8])

In [79]:
slicingDizisi = baskaDizi[4:9]

In [80]:
#slicingDizisi = 700

In [81]:
slicingDizisi

array([4, 5, 6, 7, 8])

In [82]:
type(slicingDizisi)

numpy.ndarray

In [83]:
slicingDizisi[:] = 700

In [84]:
slicingDizisi

array([700, 700, 700, 700, 700])

In [85]:
baskaDizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [86]:
ornekDizi = np.arange(0,24)

In [87]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [88]:
ornekDiziKopyasi = ornekDizi.copy()

In [89]:
ornekDiziKopyasi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

**Matrix**

In [90]:
ornekMatrixDizisi = np.arange(0,9)

In [91]:
benimMatrixDizim = np.array(ornekMatrixDizisi)

In [92]:
benimMatrixDizim

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [93]:
benimMatrixDizim.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [94]:
benimMatrixDizim[0]

0

In [98]:
benimMatrixDizim[1:2]

array([1])