<a href="https://colab.research.google.com/github/Ardaazimtsz/BTK-Veri-Bilimi-icin-Python-ve-Tensorflow/blob/main/3-MNIST_YSA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**MNIST VERİ KÜMESİNİ KULLANARAK YAPAY SİNİR AĞLARI İLE RAKAM SINIFLANDIRMA**

## **MNIST VERİ KÜMESİNİ YÜKLEMEK**

---



In [34]:
from keras.datasets import mnist

(train_images, train_labels),(test_images,test_labels) = mnist.load_data()

In [35]:
train_images.shape

(60000, 28, 28)

In [36]:
len(train_images)

60000

In [37]:
train_images

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [38]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [39]:
test_images.shape

(10000, 28, 28)

In [40]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

## **YAPAY SİNİR AĞI MİMARİSİ**

In [41]:
from keras import models
from keras import layers

In [42]:
network = models.Sequential()
network.add(layers.Dense(512, activation="relu", input_shape=(28*28,)))
network.add(layers.Dense(10, activation="softmax"))

## **YSA MODELİNİN DERLENMESİ**

In [43]:
network.compile(optimizer="rmsprop", loss="categorical_crossentropy", metrics=["accuracy"])

## **GİRİŞLERİN VE ETİKETLERİN HAZIRLANMASI**

In [44]:
train_images = train_images.reshape((60000, 28*28))
train_images = train_images.astype("float32") / 255

test_images = test_images.reshape((10000, 28*28))
test_images = test_images.astype("float32") / 255

In [45]:
from keras.utils import to_categorical
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

## **YSA MODELİNİN EĞİTİLMESİ**

In [47]:
network.fit(train_images, train_labels, epochs=10, batch_size=128)

Epoch 1/10
469/469 [==============================] - 5s 11ms/step - loss: 0.0297 - accuracy: 0.9913
Epoch 2/10
469/469 [==============================] - 4s 9ms/step - loss: 0.0224 - accuracy: 0.9938
Epoch 3/10
469/469 [==============================] - 4s 9ms/step - loss: 0.0181 - accuracy: 0.9952
Epoch 4/10
469/469 [==============================] - 5s 11ms/step - loss: 0.0134 - accuracy: 0.9966
Epoch 5/10
469/469 [==============================] - 4s 9ms/step - loss: 0.0099 - accuracy: 0.9976
Epoch 6/10
469/469 [==============================] - 4s 9ms/step - loss: 0.0077 - accuracy: 0.9983
Epoch 7/10
469/469 [==============================] - 5s 11ms/step - loss: 0.0054 - accuracy: 0.9988
Epoch 8/10
469/469 [==============================] - 4s 9ms/step - loss: 0.0041 - accuracy: 0.9992
Epoch 9/10
469/469 [==============================] - 4s 9ms/step - loss: 0.0031 - accuracy: 0.9995
Epoch 10/10
469/469 [==============================] - 5s 11ms/step - loss: 0.0018 - accuracy: 0.

In [48]:
test_loss, test_acc = network.evaluate(test_images,test_labels)

313/313 [==============================] - 2s 5ms/step - loss: 0.0698 - accuracy: 0.9829


In [49]:
print("test_loss: ",test_loss)

test_loss:  0.06980928778648376


In [50]:
print("test_acc: ",test_acc)

test_acc:  0.9829000234603882
